[metadata]
name = erpnext-commerce
version = 0.1.0
description = ERPNext customization for commercial/trading companies
long_description = file: README.md
long_description_content_type = text/markdown
author = Aleph Tech JSC
author_email = dev@alephtech.com
license = MIT

[options]
packages = find:
include_package_data = True
python_requires = >=3.10

[options.package_data]
* = *.json, *.csv, *.txt, *.html, *.css, *.js, *.png, *.jpg
